# Generated by Django 2.2 on 2022-01-26 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='body',
            field=models.DateTimeField(),
        ),
    ]
